import json
from dataclasses import dataclass
from typing import Iterable

import psycopg

from avito_scraper import settings


@dataclass
class Item:
    """Сущность товара."""

    name: str
    article: int
    url: str
    attrs: dict

    def __eq__(self, other) -> bool:
        """Переопределенный метод для возможности формирования сетов товаров."""
        if isinstance(other, Item):
            return (self.article,) == (
                other.article,
            )
        return False

    def __hash__(self) -> int:
        """Переопределенный метод для возможности формирования сетов товаров."""
        return hash(self.article)


def init_schema() -> None:
    """Инициализирует схему в базу данных."""
    with psycopg.connect(settings.PG_DSN) as connection, psycopg.ClientCursor(
        connection,
    ) as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                article INT UNIQUE NOT NULL,
                name TEXT NOT NULL,
                attrs JSONB NOT NULL,
                created_at TIMESTAMP DEFAULT NOW() NOT NULL,
                url TEXT NOT NULL
            );
        """)
        connection.commit()


def mogrify_items(cursor, items: Iterable[Item]):
    """Формирует список вставляемых значений в базу данных.
    Данный метод является значительно более производительым по сравению с cursor.executemany.
    """
    for item in items:
        yield cursor.mogrify(
            "(%s,%s,%s,%s)",
            (item.article, item.name, json.dumps(item.attrs), item.url),
        )


def insert_items(items: Iterable[Item]) -> None:
    """Заносит список товаров в базу данных."""
    with psycopg.connect(settings.PG_DSN) as connection, psycopg.ClientCursor(
        connection,
    ) as cursor:
        if not items:
            print("Ошибка: список товаров пуст.")
            return  # Завершение выполнения функции, если список пуст
        values = ",".join(mogrify_items(cursor, items))
        cursor.execute(
            f"""INSERT INTO items (article, name, attrs, url) VALUES {values}"""
        )  # type: ignore
        connection.commit()

